### ISSUE TITLE
Infinite Stream does run forever

### ISSUE THREAD

**Issue by NobbZ** [beatrichartz/parallel_stream#1]
I have an infinite stream comming in and want to `map` over it, then `filter`
and as a last step I have a simple `Enum.take(1)`.

Using stdlib `Stream` functions, my tests finish after a couple of seconds,
using ParallelStream my testsuite does time out.

When I'm back home this evening, I'll try to add some example to reproduce the
behaviour.

**Comment by NobbZ** [comment]
Oh dear, it doesn't run forever... My problem s somewhere else and seems to be related to the fact that I'm piping multiple parallel streams into each other.

When I only use parallel stream for the most expensive transformation (calculating MD5) runtime drops drastically and it finishes before testsuite times out. It is still much slower than using Stream.map/2 at the same place. 

I will try to put up a benchmarking project tomorrow that shows my usecase as it is.

**Comment by beatrichartz** [comment]
Sounds interesting, thanks for raising this. Looking forward to seeing some code replicating the issue!

**Comment by beatrichartz** [comment]
I think you hit a case where parallelism yields diminishing returns. Calculating an md5 of a short string is _very_ fast, so parallelism adds more overhead than it benefits you.

I've added a benchmark case [here](https://github.com/beatrichartz/parallel_stream/blob/master/bench/bench.exs) with a `:timer.sleep(1)` which shows that for computations taking a certain time (`:timer.sleep` is not really accurately sleeping 1 millisecond due to system limitations, but that does not matter), parallelism will be faster. If you substitute the `:timer.sleep` in the benchmark case with an `:erlang.md5` computation, you'll see that md5 is computed in microseconds (on most modern CPUs md5 is more or less a single operation). I think the cutoff for parallelism with this library to be beneficial will lie somewhere in the sub-millisecond / microsecond area, but I haven't tested it yet.

Also, maybe there is some potential to lower that cutoff further - I'll have a look at that as soon as I find the time.

**Comment by beatrichartz** [comment]
I've found a better illustration and added it to the benchmark example: `:erlang.md5(:crypto.strong_rand_bytes(32))` - if you increase the randomly generated bytes / length of string to 512, you'll see non-parallelism and parallelism get even in terms of performance.

**Comment by beatrichartz** [comment]
Cleaned the benchmark up a little bit, so it prints the average function call time - I've found the cutoff to be around 20 microseconds on my machine (`i7-3720QM CPU @ 2.60GHz`):

```
Settings:
  duration:      1.0 s

## Bench
Function call is taking ~16.71 microseconds

[11:35:14] 1/2: stream
[11:35:16] 2/2: parallel_stream

Finished in 3.63 seconds

## Bench
parallel_stream          10   146614.90 µs/op
stream                   10   163775.00 µs/op
```

In a real world example there will be more context switching etc so your mileage will vary. In contrast, for a md5 computation of a short string which takes about 1 microsecond per call, this lib will be about 10 - 12 times slower than stream:

```
Settings:
  duration:      1.0 s

## Bench
Function call is taking ~1.02 microseconds

[11:37:39] 1/2: stream
[11:37:43] 2/2: parallel_stream

Finished in 5.06 seconds

## Bench
stream                  500   6263.63 µs/op
parallel_stream          10   106860.40 µs/op
```

Feel free to reopen if your example involves a bug. I opened https://github.com/beatrichartz/parallel_stream/issues/2 to look at lowering the overhead of parallelism, though I feel that the current cutoff is already quite good.
